import localFont from 'next/font/local';
// import { cookies, headers } from 'next/headers';

import * as S from '@/app/globals.css';
import Providers from '@/app/providers';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

import type { Metadata, Viewport } from 'next';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.ico',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const cookie = cookies()
  // cookie.get('access')
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Header />
          <div className={S.container}>{children}</div>
          <Footer />
        </Providers>
        <div id="root-portal" />
      </body>
    </html>
  );
}
